version: '3.8'

services:
  project.one.jobconnect:
    image: project.one.jobconnect
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/project_db
      SPRING_DATA_MONGODB_PORT: 27017
    networks:
      - my-network

  mongodb:
    image: mongo:noble
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: project_db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      retries: 5
      start_period: 30s
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
